<div class="project">
    <div class="horizontal split">
        <div class="add before">+</div>
        <div class="vertical split">
            <div class="add before">+</div>
            <div class="image">
                <div>Vert.</div>
                <div>Hor.</div>
            </div>
            <div class="image">
                <img src="1.jpg" alt="img5" data-id="5" />
            </div>
            <div class="add after">+</div>
        </div>
        <div class="vertical split">
            <div class="add before">+</div>
            <div class="image">
                <img src="2.jpg" alt="img6" data-id="6" />
            </div>
            <div class="image">
                <div>Vert.</div>
                <div>Hor.</div>
            </div>
            <div class="add after">+</div>
        </div>
        <div class="add after">+</div>
    </div>
</div>