DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS image;
DROP TABLE IF EXISTS collection;

CREATE TABLE collection (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(30) UNIQUE NOT NULL,
  date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE image (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(30) UNIQUE NOT NULL,
  collection_id INTEGER NOT NULL REFERENCES collection(id) ON DELETE CASCADE
);

CREATE TABLE project (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(30) UNIQUE NOT NULL,
  collection_id INTEGER NOT NULL REFERENCES collection(id) ON DELETE CASCADE,
  date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  body JSON
);

# body field must be inserted manually just after the project creation!
